### ISSUE TITLE
Bug: Auto-tp to spawn on join plugins conflict.

### ISSUE THREAD

**Issue by xNul** [nyvaria/OpenAnalytics#7]
Hey captbunzo, while trying to add a plugin to auto-tp to spawn on join I realized that every single one I've tried (that works), conflicts with OpenAnalytics.  This only occurs on a multiworld server (I'm using multiverse, not sure if it matters) when you are on a different world than the spawn world.  The auto-tp plugin is unaffected, but your plugin returns an error.

```
11:09:43 PM [SEVERE] Could not pass event PlayerChangedWorldEvent to OpenAnalytics v1.0.03
11:09:43 PM org.bukkit.event.EventException
11:09:43 PM     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.PlayerList.moveToWorld(PlayerList.java:526) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.craftbukkit.v1_7_R1.entity.CraftPlayer.teleport(CraftPlayer.java:467) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.craftbukkit.v1_7_R1.entity.CraftEntity.teleport(CraftEntity.java:200) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at me.Jonaschecker.spawntp.SpawnTP.onJoin(SpawnTP.java:172) [spawn-tp.jar:?]
11:09:43 PM     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_25]
11:09:43 PM     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_25]
11:09:43 PM     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_25]
11:09:43 PM     at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_25]
11:09:43 PM     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.PlayerList.c(PlayerList.java:225) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.PlayerList.a(PlayerList.java:116) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.LoginListener.c(LoginListener.java:78) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.LoginListener.a(LoginListener.java:42) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:149) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM Caused by: java.lang.NullPointerException
11:09:43 PM     at net.nyvaria.openanalytics.OpenAnalyticsTracker.trackPlayerChangedWorld(OpenAnalyticsTracker.java:121) ~[?:?]
11:09:43 PM     at net.nyvaria.openanalytics.listener.OpenAnalyticsListener.onPlayerChangedWorld(OpenAnalyticsListener.java:69) ~[?:?]
11:09:43 PM     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_25]
11:09:43 PM     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_25]
11:09:43 PM     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_25]
11:09:43 PM     at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_25]
11:09:43 PM     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
11:09:43 PM     ... 26 more
```

If you want to try to replicate it, I get the error using [Spawn-TP](http://dev.bukkit.org/bukkit-plugins/spawn-tp/).

1.) Join server and set server spawn with /setspawn
2.) Teleport to a different world
3.) Disconnect from server
4.) Connect to server

and you should see the error in your console.

Thanks for your plugin.  This is the only issue I've had so far, and the plugin itself is extremely useful to me!

**Comment by captbunzo** [comment]
Thanks for the report. I'm a bit busy atm, but will look into sorting this as soon as possible.

**Comment by xNul** [comment]
Great, appreciate it!

**Comment by xNul** [comment]
Can you please fix the bug?

**Comment by GabbySilver** [comment]
But that's how we tell if our server is running or not when she up and decides to hang up without telling us. 
I'm kidding, I swear. I'll bug the capt and remind him that something was said about this a year ago, but  I don't know how much good it will do, considering that he's setting up house on continent number three right now.

**Comment by xNul** [comment]
Haha, ok thanks.  I appreciate it
