### ISSUE TITLE
ConcurrentModificationException on logout

### ISSUE THREAD

**Issue by Eelviny** [nyvaria/OpenAnalytics#8]
No idea what's causing it, so I'll just place the error here.

```
[22:27:55 INFO]: MCMashedPotato left the game.
[22:27:55 WARN]: Exception in thread "Craft Scheduler Thread - 1005" 
[22:27:55 WARN]: org.apache.commons.lang.UnhandledException: Plugin OpenAnalytics v1.0.03 generated an exception while executing task 28
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
        at java.util.HashMap$ValueIterator.next(HashMap.java:954)
        at net.nyvaria.openanalytics.OpenAnalyticsTracker$ScheduledAsynchronousTask.run(OpenAnalyticsTracker.java:138)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:67)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by captbunzo** [comment]
Is this a recurring problem?

**Comment by Eelviny** [comment]
To be honest, I've only seen it once in my 4 days since I started using this plugin, so it's not a very high priority fix.
I just put it here so you know.

**Comment by captbunzo** [comment]
Thanks for the feedback. I suspect this is one of those edge case scenario kinda things. It is good to know it's not happening all the time. I'll take a look next time I'm coding away at this plugin and see if I can track down a cause.

(note to self. revisit this link later... http://www.javacodegeeks.com/2011/05/avoid-concurrentmodificationexception.html)

**Comment by Eelviny** [comment]
```
[19:44:02 INFO]: JayLegoMine14 left the game.
[19:44:02 WARN]: Exception in thread "Craft Scheduler Thread - 782" 
[19:44:02 WARN]: org.apache.commons.lang.UnhandledException: Plugin OpenAnalytics v1.0.03 generated an exception while executing task 28
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
        at java.util.HashMap$ValueIterator.next(HashMap.java:954)
        at net.nyvaria.openanalytics.OpenAnalyticsTracker$ScheduledAsynchronousTask.run(OpenAnalyticsTracker.java:138)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:67)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

I'm actually starting to see this more and more. I had only really seen it once as
1. I can't monitor console 24/7 
2. I had only started using this plugin
3. Logouts don't happen as often as many other events.

**Comment by GabbySilver** [comment]
Thank you for posting this, Eelviny. As somebody who deals with the front end of Capt's plugins from time to time I've got to ask, is this causing a reaction other than the error message?

**Comment by Eelviny** [comment]
@GabbySilver, I'm finding that this has no other adverse effects on the server, apart from spamming console a bit. But, I'm taking a guess and saying that this action is not being sent to Analytics when this occurs.
So, still low priority really.
